# Generated by Django 6.0.6 on 2026-06-21 06:04

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('expertise', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='experts/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CRITICAL', '🔴 Critical'), ('HIGH', '🟠 High'), ('MEDIUM', '🟡 Medium'), ('LOW', '🟢 Low')], default='MEDIUM', max_length=10)),
                ('color', models.CharField(default='#FF4444', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('POLICY', 'Draft Policy'), ('REFERENCE', 'Reference'), ('INFOGRAPHIC', 'Infographic'), ('PLAYBOOK', 'Playbook')], max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short summary shown in cards')),
                ('content', ckeditor.fields.RichTextField(help_text='Full article content with formatting')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, help_text='e.g., Lusaka, Ndola, Livingstone', max_length=200)),
                ('statistic_value', models.CharField(blank=True, help_text='e.g., 34%', max_length=50)),
                ('statistic_change', models.CharField(blank=True, help_text='e.g., ↑ 12% in 6m', max_length=20)),
                ('statistic_label', models.CharField(blank=True, help_text='e.g., ICU Resistance', max_length=100)),
                ('cost_estimate', models.CharField(blank=True, help_text='e.g., $47 Million', max_length=100)),
                ('cost_description', models.CharField(blank=True, help_text='e.g., extra beds', max_length=200)),
                ('action_items', models.TextField(blank=True, help_text='Bullet points of action items')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='research_images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='research_pdfs/')),
                ('infographic', models.FileField(blank=True, null=True, upload_to='infographics/')),
                ('views_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_alert', models.BooleanField(default=False, help_text='Show as CRITICAL ALERT')),
                ('references', models.TextField(blank=True, help_text='Reference links or citations')),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.sector')),
                ('threat_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.threatlevel')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
